name: Docker Image CI

on:
  push:
    branches: [ update-docker-compose-config ]
  pull_request:
    branches: [ update-docker-compose-config ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up
